#!/bin/bash
# Auto-generated by team-leader — task 005: Design rounding to significant digits exercise
cd "$(dirname "$0")"
echo "━━━ Task 005: Design rounding to significant digits exercise ━━━"
echo "Task file: .tasks/items/005-rounding-sigfigs.md"
exec opencode
